services:
  redis:
    image: redis:7.4.2
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    ports:
      - "6379:6379"
  api:
    build:
      context: ./api
      target: development
    ports:
      - "3001:3001"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
    develop:
      watch:
        - action: sync
          path: ./api/src
          target: /app/src
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
  app:
    build:
      context: ./app
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
          ignore:
            - node_modules
            - .next
        - action: rebuild
          path: package.json