version: "3.8"

services:
  redis:
    image: redis:7.4.2
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - traefik-public

  api:
    image: ghcr.io/isaacbatst/golpe-api:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.congressosimulator.com.br`)"
      - "traefik.http.services.api.loadbalancer.server.port=3001"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
    secrets:
      - session-secret
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REDIS_URL=redis://redis:6379
      - SESSION_SECRET_FILE=/run/secrets/session-secret
      - SESSION_SECURE=true
      - SESSION_DOMAIN=.congressosimulator.com.br
      - CORS_ORIGIN=https://congressosimulator.com.br
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 30s
    depends_on:
      - redis
    networks:
      - traefik-public

  app:
    image: ghcr.io/isaacbatst/golpe-app:${GIT_COMMIT_HASH:-latest}
    deploy:
      update_config:
        order: start-first      
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`congressosimulator.com.br`)"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
    depends_on:
      - api
    networks:
      - traefik-public

secrets:
  session-secret:
    external: true

volumes:
  letsencrypt:

networks:
  traefik-public:
    external: true
