name: pipeline-api
on:
  push:
    branches:
      - "main"
    paths:
      - "api/**"
  

permissions:
  packages: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: |
          cd ./api
          npm clean-install
      - name: Test with the Node.js CLI
        run: |
          cd ./api
          npm test

  build-and-push:
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for API
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: |
            ghcr.io/isaacbatst/golpe-api:latest
            ghcr.io/isaacbatst/golpe-api:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: create env file
      run: |
        echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile

    - name: Docker Stack Deploy
      uses: cssnr/stack-deploy-action@v1
      with:
        name: golpe
        file: stack.yaml
        host: congressosimulator.com.br
        user: golpe
        ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        env_file: ./envfile